version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Installing get-profile dependencies"
      - cd get-profile && npm install && cd ..
      - echo "Installing post-profile dependencies"
      - cd post-profile && npm install && cd ..
  build:
    commands:
      - echo "Running tests in get-profile"
      - cd get-profile && npm test && cd ..
      - echo "Packaging app"
      - sam package --region us-east-2 --s3-bucket mandia-storage --s3-prefix profile-sam --output-template-file package.yaml
artifacts:
  files:
    - package.yaml
  name: profileApp-$(date +%Y-%m-%d-%H%M%S)
    